[phases.setup]
nixPkgs = ['dotnet-sdk_9']

[phases.build]
cmds = [
  'dotnet restore SuperMarket.API/SuperMarket.API.csproj',
  'dotnet publish SuperMarket.API/SuperMarket.API.csproj -c Release -o out --no-restore'
]

[start]
cmd = 'dotnet out/SuperMarket.API.dll'
